version: '3.8'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  graphdb:
      image: khaller/graphdb-free:10.0.0
      container_name: graphdb-free
      ports:
        - "7200:7200"
      volumes:
        - ./repository.init:/repository.init