version: "3.9"

services:
    devcontainer:
        image: mcr.microsoft.com/devcontainers/base:jammy
        volumes:
          # Update this to wherever you want VS Code to mount the folder of your project
          - ../..:/workspaces:cached
        # Overrides default command so things don't shut down after the process ends.
        entrypoint: /usr/local/share/docker-init.sh
        command: sleep infinity 
    graphdb:
      image: khaller/graphdb-free:10.0.0
      container_name: graphdb-free
      ports:
        - "7200:7200"
      volumes:
        - ./repository.init:/repository.init
        - ${LOCAL_WORKSPACE_FOLDER:-.}/repository.init:/repository.init
