version: "3.9"

services:
    graphdb:
      image: khaller/graphdb-free:10.0.0
      container_name: graphdb-free
      ports:
        - "7200:7200"
      volumes:
        - ${LOCAL_WORKSPACE_FOLDER:-.}/repository.init:/repository.init
